let country = "India";
let continent = "Asia";
let population = 1400000000;
console.log(country);
console.log(continent);
console.log(population);
let isIsland = false;
const language = "Hindi";
console.log(isIsland);
console.log(language);
